name: the_first
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.8   # أحدث إصدار مستقر

  # Packages لإدارة الصلاحيات
  permission_handler: ^11.0.1
  shared_preferences: ^2.2.2
  app_settings: ^6.1.1  # لفتح إعدادات التطبيق
  device_info_plus: ^10.1.0
  universal_html: ^2.2.1
  path_provider: ^2.1.3
    # Packages موجودة
  debounce_throttle: ^2.0.0
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.8
  path: ^1.8.3
    # للويب (اختياري):
  file_picker: ^10.3.8




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Calibri
      fonts:
        - asset: fonts/calibrib.ttf
          weight: 700
    - family: Cairo
      fonts:
        - asset: fonts/Cairo.ttf
          weight: 700
    - family: NotoKufi
      fonts:
        - asset: fonts/NotoKufi.ttf
          weight: 700